// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57wwn4Wk2Ic0FreV-aAi6Q37DOE60unw',
    appId: '1:1073707531103:web:dc15065de1c5b1fd5214ea',
    messagingSenderId: '1073707531103',
    projectId: 'chat-app-c47e9',
    authDomain: 'chat-app-c47e9.firebaseapp.com',
    storageBucket: 'chat-app-c47e9.appspot.com',
    measurementId: 'G-KXNCR41HB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3lDZJa-aD9sRLmWvHCItT5EPxxabpnLc',
    appId: '1:1073707531103:android:6dfa710916c77a2e5214ea',
    messagingSenderId: '1073707531103',
    projectId: 'chat-app-c47e9',
    storageBucket: 'chat-app-c47e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV9-skJ6BtFb0bJHymTfDExQh-VVT66Nk',
    appId: '1:1073707531103:ios:572ea537dcdf12d85214ea',
    messagingSenderId: '1073707531103',
    projectId: 'chat-app-c47e9',
    storageBucket: 'chat-app-c47e9.appspot.com',
    iosClientId: '1073707531103-n083m4ig0cd60f98bo4tf716vht1o3ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV9-skJ6BtFb0bJHymTfDExQh-VVT66Nk',
    appId: '1:1073707531103:ios:40016f5cbb412f005214ea',
    messagingSenderId: '1073707531103',
    projectId: 'chat-app-c47e9',
    storageBucket: 'chat-app-c47e9.appspot.com',
    iosClientId: '1073707531103-7i6ftj74jesohia4kqdqe1q1metp2n4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
