// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGEyDOVOWkcgSI-7C4aUISWjEP2EM5Ks8',
    appId: '1:211707368384:web:40b97d8575ba718311ae25',
    messagingSenderId: '211707368384',
    projectId: 'instagram-clone-7eaf3',
    authDomain: 'instagram-clone-7eaf3.firebaseapp.com',
    storageBucket: 'instagram-clone-7eaf3.appspot.com',
    measurementId: 'G-N5DENQSK25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoKAtktDboMnx__dPd0u0jf57WCA8UWZE',
    appId: '1:211707368384:android:8806deff047fb08f11ae25',
    messagingSenderId: '211707368384',
    projectId: 'instagram-clone-7eaf3',
    storageBucket: 'instagram-clone-7eaf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8foh82JHekNLdJxztP9sOEO9iSc6SFY',
    appId: '1:211707368384:ios:99f29cf4430a3fdb11ae25',
    messagingSenderId: '211707368384',
    projectId: 'instagram-clone-7eaf3',
    storageBucket: 'instagram-clone-7eaf3.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP8foh82JHekNLdJxztP9sOEO9iSc6SFY',
    appId: '1:211707368384:ios:a828b9684834a1ca11ae25',
    messagingSenderId: '211707368384',
    projectId: 'instagram-clone-7eaf3',
    storageBucket: 'instagram-clone-7eaf3.appspot.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
